import Head from 'next/head'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import strapi from '../../utilities/strapi-api';
import LanguageToggle from '../../components/localization/languageToggle';
import Link from 'next/link';


export default function Home({ id, attributes }) {
    const { t } = useTranslation();

    return (
        <>
            <Head>
                <title>Test Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <LanguageToggle />
                <h1>TEST</h1>
                <div>
                    CONTENT: {attributes.mainCopy}
                </div>
                <div>
                    TRANSLATION: {t('hello')}
                </div>
                <button>
                    <Link href={"/"} >
                        HOME PAGE
                    </Link>
                </button>

            </main>
        </>
    )
}



export async function getStaticProps({ locale }) {
    /// Replace <content> with the api route you want
    const { data } = await strapi.get(`<content>?locale=${locale}`)

    return {
        props: {
            ...(await serverSideTranslations(locale, [
                'common',
            ])),
            // Will be passed to the page component as props
            id: data.id,
            attributes: data.attributes,
        },
    }
}
